roi_topic_name: "/darknet_ros/bounding_boxes"
depth_image_topic_name: "/theia/front_camera/aligned_depth_to_color/image_raw"
cam_info_topic_name: "/theia/front_camera/aligned_depth_to_color/camera_info"